sudo: required
services:
  - docker


before_intall:
 - docker build -t sen4senan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sen4senan/docker-react npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-605035613673"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
